name: assigmentflutterone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  google_maps_flutter: ^2.10.0
  geocoding: ^3.0.0
  location: ^7.0.1
  shared_preferences: ^2.3.4
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  path_provider: ^2.1.5
  flutter_bounceable: ^1.1.0
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.6
  intl: ^0.20.1
  sqflite: ^2.4.1
  quickalert: ^1.1.0
  path: ^1.9.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_svg_provider: ^1.0.7



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/debit/
    - assets/svg/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconapp.jpg"